import React, { useState } from 'react'

export const data =  {
        "data": {                                                                                                                                                     
            "totalCount": 116,
            "items": [ 
                {
                    "userId": "BFE5A09A-16E5-EE11-AAF0-6045BDD3029E",
                    "emailId": "testdisinvite@yopmail.com",
                    "displayId": "DIS0185",
                    "status": "INVITED",
                    "userType": "DISTRIBUTOR",
                    "joinedDate": "2024-03-18T10:59:35.130Z",
                    "profileId": "C0E5A09A-16E5-EE11-AAF0-6045BDD3029E",
                    "companyName": "Test Dis Invite",
                    "phoneNumber": "9876543210",
                    "website": null,
                    "primaryContactName": "Distributor TR Contact Person",
                    "address": null,
                    "activationKey": null,
                    "posProvider": null,
                    "websiteProvider": null,
                    "licenceNumber": null,
                    "licenceType": null,
                    "ipAddress": null,
                    "inventoryManagementSystem": null,
                    "additionalOrderFulfillmentSoftware": null,
                    "minimumOrderThresholds": null,
                    "numberOfStoreLocations": null,
                    "orderCutOffTime": null, 
                    "monthlySalesSort": 0,
                    "monthlyOrders": 0,
                    "noOfOrders": 0,
                    "noOfMappedRetailers": 0,
                    "monthlySales": "$0.00"
                },
                {
                    "userId": "AE32BFB2-15E5-EE11-AAF0-6045BDD3029E",
                    "emailId": "testdisemails@yopmail.com",
                    "displayId": "DIS0185",
                    "status": "ACTIVE",
                    "userType": "DISTRIBUTOR",
                    "userType": "2024-03-18T10:53:06.110Z",
                    "profileId": "AF32BFB2-15E5-EE11-AAF0-6045BDD3029E",
                    "companyName": "Test Dis Emails",
                    "phoneNumber": "9876543210",
                    "website": "www.wineview1.com",
                    "primaryContactName": "Distributor TR Contact Person",
                    "address": "No.121, Distributortr Street, Birmingham, Alabama, United States.",
                    "activationKey": null,
                    "posProvider": null,
                    "websiteProvider": null,
                    "licenceNumber": null,
                    "licenceType": null,
                    "ipAddress": null,
                    "inventoryManagementSystem": null,
                    "additionalOrderFulfillmentSoftware": null,
                    "minimumOrderThresholds": null,
                    "numberOfStoreLocations": null,
                    "orderCutOffTime": null,
                    "monthlySalesSort": 0,
                    "monthlyOrders": 0,
                    "noOfOrders": 0,
                    "noOfMappedRetailers": 2,
                    "monthlySales": "$0.00"
                },
                {
                    "userId": "4403CA8C-13E5-EE11-AAF0-6045BDD3029E",
                    "emailId": "testdist92cdf@gmail.com",
                    "displayId": "DIS0185",
                    "status": "-",
                    "userType": "DISTRIBUTOR",
                    "joinedDate": "2024-03-18T10:37:43.433Z",
                    "profileId": "4503CA8C-13E5-EE11-AAF0-6045BDD3029E",
                    "companyName": "TESTDIST92cdf",
                    "phoneNumber": "1111111111",
                    "website": "https://jwt.io/",
                    "primaryContactName": "TESTDIST92cdf",
                    "address": "TESTDIST92cdf",
                    "activationKey": null,
                    "posProvider": null,
                    "websiteProvider": null,
                    "licenceNumber": null,
                    "licenceType": null,
                    "ipAddress": null,
                    "inventoryManagementSystem": null,
                    "additionalOrderFulfillmentSoftware": null,
                    "minimumOrderThresholds": null,
                    "numberOfStoreLocations": null,
                    "orderCutOffTime": null,
                    "monthlySalesSort": 0,
                    "monthlyOrders": 0,
                    "noOfOrders": 0,
                    "noOfMappedRetailers": 0,
                    "monthlySales": "$0.00"
                },
                {
                    "userId": "06368417-13E5-EE11-AAF0-6045BDD3029E",
                    "emailId": "testdist92cdfv@gmail.com",
                    "displayId": "DIS0185",
                    "status": "-",
                    "userType": "DISTRIBUTOR",
                    "joinedDate": "2024-03-18T10:34:26.663Z",
                    "profileId": "07368417-13E5-EE11-AAF0-6045BDD3029E",
                    "companyName": "TESTDIST92CDFV",
                    "phoneNumber": "1111111111",
                    "website": "https://jwt.io/",
                    "primaryContactName": "TESTDIST92CDFV",
                    "address": "TESTDIST92CDFV",
                    "activationKey": null,
                    "posProvider": null,
                    "websiteProvider": null,
                    "licenceNumber": null,
                    "licenceType": null,
                    "ipAddress": null,
                    "inventoryManagementSystem": null,
                    "additionalOrderFulfillmentSoftware": null,
                    "minimumOrderThresholds": null,
                    "numberOfStoreLocations": null,
                    "orderCutOffTime": null,
                    "monthlySalesSort": 0,
                    "monthlyOrders": 0,
                    "noOfOrders": 0,
                    "noOfMappedRetailers": 0,
                    "monthlySales": "$0.00"
                },
                {
                    "userId": "5C1B41A7-12E5-EE11-AAF0-6045BDD3029E",
                    "emailId": "test0908mkok@gmail.com",
                    "displayId": "DIS0185",
                    "status": "-",
                    "userType": "DISTRIBUTOR",
                    "joinedDate": "2024-03-18T10:31:18.330Z",
                    "profileId": "5D1B41A7-12E5-EE11-AAF0-6045BDD3029E",
                    "companyName": "TEST0908mkok",
                    "phoneNumber": "1111111111",
                    "website": "https://jwt.io/",
                    "primaryContactName": "TEST0908mkok",
                    "address": "TEST0908mkok",
                    "activationKey": null,
                    "posProvider": null,
                    "websiteProvider": null,
                    "licenceNumber": null,
                    "licenceType": null,
                    "ipAddress": null,
                    "inventoryManagementSystem": null,
                    "additionalOrderFulfillmentSoftware": null,
                    "minimumOrderThresholds": null,
                    "numberOfStoreLocations": null,
                    "orderCutOffTime": null,
                    "monthlySalesSort": 0,
                    "monthlyOrders": 0,
                    "noOfOrders": 0,
                    "noOfMappedRetailers": 0,
                    "monthlySales": "$0.00"
                },
                {
                    "userId": "5D463A51-12E5-EE11-AAF0-6045BDD3029E",
                    "emailId": "hodistbh@gmail.com",
                    "displayId": "DIS0185",
                    "status": "-",
                    "userType": "DISTRIBUTOR",
                    "joinedDate": "2024-03-18T10:28:54.003Z",
                    "profileId": "5E463A51-12E5-EE11-AAF0-6045BDD3029E",
                    "companyName": "HODISTBH",
                    "phoneNumber": "1111111111",
                    "website": "https://jwt.io/",
                    "primaryContactName": "HODISTBH",
                    "address": "HODISTBH",
                    "activationKey": null,
                    "posProvider": null,
                    "websiteProvider": null,
                    "licenceNumber": null,
                    "licenceType": null,
                    "ipAddress": null,
                    "inventoryManagementSystem": null,
                    "additionalOrderFulfillmentSoftware": null,
                    "minimumOrderThresholds": null,
                    "numberOfStoreLocations": null,
                    "orderCutOffTime": null,
                    "monthlySalesSort": 0,
                    "monthlyOrders": 0,
                    "noOfOrders": 0,
                    "noOfMappedRetailers": 0,
                    "monthlySales": "$0.00"
                },
                {
                    "userId": "D1E9F2C2-11E5-EE11-AAF0-6045BDD3029E",
                    "emailId": "testdist09vfg@gmail.com",
                    "displayId": "DIS0185",
                    "status": "-",
                    "userType": "DISTRIBUTOR",
                    "joinedDate": "2024-03-18T10:24:55.296Z",
                    "profileId": "D2E9F2C2-11E5-EE11-AAF0-6045BDD3029E",
                    "companyName": "TESTdIST09vfg",
                    "phoneNumber": "1111111111",
                    "website": "https://jwt.io/",
                    "primaryContactName": "TESTdIST09vfg",
                    "address": "TESTdIST09vfg",
                    "activationKey": null,
                    "posProvider": null,
                    "websiteProvider": null,
                    "licenceNumber": null,
                    "licenceType": null,
                    "ipAddress": null,
                    "inventoryManagementSystem": null,
                    "additionalOrderFulfillmentSoftware": null,
                    "minimumOrderThresholds": null,
                    "numberOfStoreLocations": null,
                    "orderCutOffTime": null,
                    "monthlySalesSort": 0,
                    "monthlyOrders": 0,
                    "noOfOrders": 0,
                    "noOfMappedRetailers": 0,
                    "monthlySales": "$0.00"
                },
                {
                    "userId": "0219736E-11E5-EE11-AAF0-6045BDD3029E",
                    "emailId": "testdist09lmo@gmail.com",
                    "displayId": "DIS0185",
                    "status": "-",
                    "userType": "DISTRIBUTOR",
                    "joinedDate": "2024-03-18T10:22:33.526Z",
                    "profileId": "0319736E-11E5-EE11-AAF0-6045BDD3029E",
                    "companyName": "TESTdIST09lmo",
                    "phoneNumber": "1111111111",
                    "website": "https://jwt.io/",
                    "primaryContactName": "TESTdIST09lmo",
                    "address": "TESTdIST09lmo",
                    "activationKey": null,
                    "posProvider": null,
                    "websiteProvider": null,
                    "licenceNumber": null,
                    "licenceType": null,
                    "ipAddress": null,
                    "inventoryManagementSystem": null,
                    "additionalOrderFulfillmentSoftware": null,
                    "minimumOrderThresholds": null,
                    "numberOfStoreLocations": null,
                    "orderCutOffTime": null,
                    "monthlySalesSort": 0,
                    "monthlyOrders": 0,
                    "noOfOrders": 0,
                    "noOfMappedRetailers": 0,
                    "monthlySales": "$0.00"
                },
                {
                    "userId": "69696B21-11E5-EE11-AAF0-6045BDD3029E",
                    "emailId": "testdist92ccc@gmail.com",
                    "displayId": "DIS0185",
                    "status": "-",
                    "userType": "DISTRIBUTOR",
                    "joinedDate": "2024-03-18T10:20:24.293Z",
                    "profileId": "6A696B21-11E5-EE11-AAF0-6045BDD3029E",
                    "companyName": "TESTDIST92ccc",
                    "phoneNumber": "1111111111",
                    "website": "https://jwt.io/",
                    "primaryContactName": "TESTDIST92ccc",
                    "address": "TESTDIST92ccc",
                    "activationKey": null,
                    "posProvider": null,
                    "websiteProvider": null,
                    "licenceNumber": null,
                    "licenceType": null,
                    "ipAddress": null,
                    "inventoryManagementSystem": null,
                    "additionalOrderFulfillmentSoftware": null,
                    "minimumOrderThresholds": null,
                    "numberOfStoreLocations": null,
                    "orderCutOffTime": null,
                    "monthlySalesSort": 0,
                    "monthlyOrders": 0,
                    "noOfOrders": 0,
                    "noOfMappedRetailers": 0,
                    "monthlySales": "$0.00"
                },
                {
                    "userId": "9ABB5E8C-10E5-EE11-AAF0-6045BDD3029E",
                    "emailId": "hodistka@gmail.com",
                    "displayId": "DIS0185",
                    "status": "-",
                    "userType": "DISTRIBUTOR",
                    "joinedDate": "2024-03-18T10:16:14.243Z",
                    "profileId": "9BBB5E8C-10E5-EE11-AAF0-6045BDD3029E",
                    "companyName": "HODISTka",
                    "phoneNumber": "1111111111",
                    "website": "https://jwt.io/",
                    "primaryContactName": "HODISTka",
                    "address": "HODISTka",
                    "activationKey": null,
                    "posProvider": null,
                    "websiteProvider": null,
                    "licenceNumber": null,
                    "licenceType": null,
                    "ipAddress": null,
                    "inventoryManagementSystem": null,
                    "additionalOrderFulfillmentSoftware": null,
                    "minimumOrderThresholds": null,
                    "numberOfStoreLocations": null,
                    "orderCutOffTime": null,
                    "monthlySalesSort": 0,
                    "monthlyOrders": 0,
                    "noOfOrders": 0,
                    "noOfMappedRetailers": 0,
                    "monthlySales": "$0.00"
                }
            ],
            "page": 1,
            "size": 10
        },
        "message": "User Details Found"
    }
  

